apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dating-app-ingress
  namespace: dating-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.port }}
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.userservice.name }}
            port:
              number: {{ .Values.userservice.port }}
      - path: /api/photos
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.photoservice.name }}
            port:
              number: {{ .Values.photoservice.port }}
      - path: /api/matches
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.matchservice.name }}
            port:
              number: {{ .Values.matchservice.port }}